### ISSUE TITLE
Un-identified developer

### ISSUE THREAD

**Issue by ghost** [carloscuesta/materialshell#4]
I can't use the theme. 
Here is the error that I get:
![unidentified](http://christo.js.org/img/unidentified.png)

**Comment by carloscuesta** [comment]
Hi @christoga 

Did you tried to install the theme as explained in the [readme file](https://github.com/carloscuesta/materialshell#terminal) instead of opening the file ?

`Terminal > Preferences > Gear Icon > Import > Select the theme file`

<img width="671" alt="screen shot 2016-04-13 at 19 05 22" src="https://cloud.githubusercontent.com/assets/7629661/14502247/b67ec8fa-01aa-11e6-9ef8-a957be1a686f.png">

**Comment by ghost** [comment]
Nevermind👍🏽
